spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/transaction_db
    username: transaction_user
    password: transaction_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: transactionEvent:com.devalvesg.transaction_service.adapters.dto.TransactionEvent
    topics:
      transactions-created: transactions-created
      transactions-updated: transactions-updated

logging:
  level:
    root: INFO
    com.example.transaction: DEBUG
    org.springframework.kafka: DEBUG