spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/transaction_db
    username: transaction_user
    password: transaction_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
    com.example.transaction: DEBUG
    org.springframework.kafka: DEBUG