spring:
  application:
    name: transaction-service
  profiles:
    active: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


#  kafka:
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.type.mapping: transaction:com.example.transaction.model.Transaction

server:
  port: 8080

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics,prometheus
#  metrics:
#    export:
#      prometheus:
#        enabled: true