spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/transaction_db
    username: transaction_user
    password: transaction_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: transactionEvent:com.devalvesg.transaction_service.adapters.dto.TransactionEvent
    consumer:
      group-id: transaction-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: fraudAlert:com.devalvesg.transaction_service.adapters.dto.FraudAlert
    topics:
      transactions-created: transactions-created
      transactions-updated: transactions-updated
      fraud-alerts: fraud-alerts

logging:
  level:
    root: INFO
    com.example.transaction: DEBUG
    org.springframework.kafka: DEBUG