spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/fraud_db
    username: fraud_user
    password: fraud_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
    com.example.fraud: DEBUG
    org.springframework.kafka: DEBUG